server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    gzip on;
    gzip_types text/plain text/css application/json application/javascript;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass https://xecm-production.up.railway.app/;
        proxy_set_header Host xecm-production.up.railway.app;
        proxy_ssl_server_name on;
    }
}
